services:
  mainc:
    build:
      context: .
      dockerfile: ./build/mainc.Dockerfile
    ports:
      - "8020:8020"
    networks:
      - kr-net-6-sem_kr-network
  
networks:
  kr-net-6-sem_kr-network:
    external: true