// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": [],
    "swagger": "2.0",
    "info": {
        "description": "This is a coding server for Networking.",
        "title": "Swagger API",
        "contact": {},
        "version": "1.0"
    },
    "host": "localhost:8081",
    "basePath": "/",
    "paths": {
        "/code": {
            "post": {
                "description": "Codes and decodes messages",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code"
                ],
                "summary": "Codes and decodes messages",
                "parameters": [
                    {
                        "description": "Data to process",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.DATA"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.DATA"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.DATA": {
            "type": "object",
            "required": [
                "username",
                "message_part",
                "timestamp",
                "sequence_number",
                "total_parts"
            ],
            "properties": {
                "username": {
                    "type": "string"
                },
                "message_part": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "sequence_number": {
                    "type": "integer"
                },
                "total_parts": {
                    "type": "integer"
                }
            }
        }
    }
}`

var SwaggerInfo = &swag.Spec{
    Version:          "1.0",
    Host:             "localhost:8081",
    BasePath:         "/",
    Schemes:          []string{},
    Title:            "Swagger API",
    Description:      "This is a coding server for Networking.",
    InfoInstanceName: "swagger",
    SwaggerTemplate:  docTemplate,
}

func init() {
    swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
