basePath: /
definitions:
  main.DATA:
    properties:
      data:
        type: string
      message_id:
        type: string
      segment_number:
        type: integer
      send_time:
        type: string
      socket_id:
        type: integer
      total_segments:
        type: integer
      username:
        type: string
    required:
    - data
    - message_id
    - segment_number
    - send_time
    - total_segments
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a coding server for Networking.
  title: Swagger API
  version: "1.0"
paths:
  /code:
    post:
      consumes:
      - application/json
      description: Codes and decodes messages
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/main.DATA'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Codes and decodes messages
      tags:
      - code
swagger: "2.0"
